# -*- coding: utf-8 -*-
"""Dashboard Sales and Profit Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EthyJuGfvpwd5QzfdwmnFZHpfk4RAd0D
"""

import streamlit as st
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# Memuat dataset
df = pd.read_csv('Mithilesh_Kale_superstore_sales_project-_3_.csv')

# Mengubah Order Date menjadi datetime
df['Order Date'] = pd.to_datetime(df['Order Date'])

# Mengekstrak tahun dan bulan dari Order Date
df['Year'] = df['Order Date'].dt.year
df['Month'] = df['Order Date'].dt.month

# Judul aplikasi
st.title('Dashboard Analisis Penjualan dan Laba Superstore')

# Menampilkan beberapa baris pertama dataset
st.subheader('Dataset')
st.write(df.head())

# Statistik deskriptif
st.subheader('Statistik Deskriptif')
st.write(df.describe())

# Total penjualan dan laba
total_sales = df['Sales'].sum()
total_profit = df['Profit'].sum()

st.subheader('Total Penjualan dan Laba')
st.write(f'Total Sales: {total_sales}')
st.write(f'Total Profit: {total_profit}')

# Rata-rata penjualan dan laba per pesanan
average_sales_per_order = df.groupby('Order ID')['Sales'].sum().mean()
average_profit_per_order = df.groupby('Order ID')['Profit'].sum().mean()

st.subheader('Rata-rata Penjualan dan Laba per Pesanan')
st.write(f'Rata-rata Sales per Pesanan: {average_sales_per_order}')
st.write(f'Rata-rata Profit per Pesanan: {average_profit_per_order}')

# Pendapatan dan laba per segmen pelanggan
segment_sales = df.groupby('Customer Segment')['Sales'].sum().reset_index()
segment_profit = df.groupby('Customer Segment')['Profit'].sum().reset_index()

st.subheader('Pendapatan dan Laba per Segmen Pelanggan')
fig, ax = plt.subplots(figsize=(10, 6))
sns.barplot(x='Customer Segment', y='Sales', data=segment_sales, ax=ax)
st.pyplot(fig)

fig, ax = plt.subplots(figsize=(10, 6))
sns.barplot(x='Customer Segment', y='Profit', data=segment_profit, ax=ax)
st.pyplot(fig)

# Pendapatan dan laba per kategori produk
category_sales = df.groupby('Product Category')['Sales'].sum().reset_index()
category_profit = df.groupby('Product Category')['Profit'].sum().reset_index()

st.subheader('Pendapatan dan Laba per Kategori Produk')
fig, ax = plt.subplots(figsize=(12, 6))
sns.barplot(x='Product Category', y='Sales', data=category_sales, ax=ax)
plt.xticks(rotation=45)
st.pyplot(fig)

fig, ax = plt.subplots(figsize=(12, 6))
sns.barplot(x='Product Category', y='Profit', data=category_profit, ax=ax)
plt.xticks(rotation=45)
st.pyplot(fig)

# Pendapatan dan laba per sub-kategori produk
subcategory_sales = df.groupby('Product Sub-Category')['Sales'].sum().reset_index()
subcategory_profit = df.groupby('Product Sub-Category')['Profit'].sum().reset_index()

st.subheader('Pendapatan dan Laba per Sub-Kategori Produk')
fig, ax = plt.subplots(figsize=(14, 6))
sns.barplot(x='Product Sub-Category', y='Sales', data=subcategory_sales, ax=ax)
plt.xticks(rotation=90)
st.pyplot(fig)

fig, ax = plt.subplots(figsize=(14, 6))
sns.barplot(x='Product Sub-Category', y='Profit', data=subcategory_profit, ax=ax)
plt.xticks(rotation=90)
st.pyplot(fig)

# Pendapatan dan laba per metode pengiriman
ship_mode_sales = df.groupby('Ship Mode')['Sales'].sum().reset_index()
ship_mode_profit = df.groupby('Ship Mode')['Profit'].sum().reset_index()

st.subheader('Pendapatan dan Laba per Metode Pengiriman')
fig, ax = plt.subplots(figsize=(10, 6))
sns.barplot(x='Ship Mode', y='Sales', data=ship_mode_sales, ax=ax)
plt.xticks(rotation=45)
st.pyplot(fig)

fig, ax = plt.subplots(figsize=(10, 6))
sns.barplot(x='Ship Mode', y='Profit', data=ship_mode_profit, ax=ax)
plt.xticks(rotation=45)
st.pyplot(fig)

# Tren penjualan per tahun
yearly_sales = df.groupby('Year')['Sales'].sum().reset_index()
yearly_profit = df.groupby('Year')['Profit'].sum().reset_index()

st.subheader('Tren Penjualan dan Laba per Tahun')
fig, ax = plt.subplots(figsize=(10, 6))
sns.lineplot(x='Year', y='Sales', data=yearly_sales, ax=ax)
st.pyplot(fig)

fig, ax = plt.subplots(figsize=(10, 6))
sns.lineplot(x='Year', y='Profit', data=yearly_profit, ax=ax)
st.pyplot(fig)

# Tren penjualan per bulan
monthly_sales = df.groupby(['Year', 'Month'])['Sales'].sum().reset_index()
monthly_profit = df.groupby(['Year', 'Month'])['Profit'].sum().reset_index()

st.subheader('Tren Penjualan dan Laba per Bulan')
fig, ax = plt.subplots(figsize=(12, 6))
sns.lineplot(x='Month', y='Sales', hue='Year', data=monthly_sales, ax=ax)
plt.xticks(rotation=45)
st.pyplot(fig)

fig, ax = plt.subplots(figsize=(12, 6))
sns.lineplot(x='Month', y='Profit', hue='Year', data=monthly_profit, ax=ax)
plt.xticks(rotation=45)
st.pyplot(fig)

# Distribusi penjualan
st.subheader('Distribusi Penjualan')
fig, ax = plt.subplots(figsize=(10, 6))
sns.histplot(df['Sales'], bins=30, kde=True, ax=ax)
st.pyplot(fig)

# Hubungan antara penjualan dan laba
st.subheader('Hubungan antara Penjualan dan Laba')
fig, ax = plt.subplots(figsize=(10, 6))
sns.scatterplot(x='Sales', y='Profit', data=df, ax=ax)
st.pyplot(fig)

# Distribusi profit berdasarkan segmen pelanggan
st.subheader('Distribusi Profit Berdasarkan Segmen Pelanggan')
fig, ax = plt.subplots(figsize=(10, 6))
sns.boxplot(x='Customer Segment', y='Profit', data=df, ax=ax)
plt.xticks(rotation=45)
st.pyplot(fig)

# Copyright
st.caption("© 2024 Bayu Puspito Aji. All rights reserved.")